apiVersion: v1
kind: Pod
metadata:
    name: tools
    annotations:
        sidecar.istio.io/inject: "true"
    labels:
        name: tools
spec:
    containers:
        - name: tools
          image: tadamo/tools:latest
          imagePullPolicy: Always
          command: ["tail", "-f", "/dev/null"]
          env:
              - name: NODE_NAME
                valueFrom:
                    fieldRef:
                        fieldPath: spec.nodeName
              - name: POD_NAME
                valueFrom:
                    fieldRef:
                        fieldPath: metadata.name
              - name: POD_NAMESPACE
                valueFrom:
                    fieldRef:
                        fieldPath: metadata.namespace
              - name: POD_IP
                valueFrom:
                    fieldRef:
                        fieldPath: status.podIP
              - name: POD_SERVICE_ACCOUNT
                valueFrom:
                    fieldRef:
                        fieldPath: spec.serviceAccountName
          resources:
              requests:
                  cpu: 100m
                  memory: 100Mi
              limits:
                  cpu: 200m
                  memory: 200Mi
