apiVersion: v1
kind: Pod
metadata:
  name: tools
spec:
  containers:
  - name: tools
    image: tadamo/tools:latest
    imagePullPolicy: Always
    command:
      - sleep
      - "1000000"
    resources:
      limits:
        cpu: 20m
        memory: 50Mi
      requests:
        cpu: 20m
        memory: 50Mi
