---
apiVersion: v1
kind: Service
metadata:
    name: tools-http
    labels:
        name: tools-http
spec:
    selector:
        name: tools-http
    ports:
        - name: http
          port: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: tools-http
spec:
    replicas: 1
    selector:
        matchLabels:
            name: tools-http
    template:
        metadata:
            annotations:
                sidecar.istio.io/inject: "true"
                kubernetes.io/ingress-bandwidth: 100M
                kubernetes.io/egress-bandwidth: 100M
            labels:
                name: tools-http
        spec:
            containers:
                - name: tools-http
                  image: tadamo/tools:latest
                  imagePullPolicy: Always
                  command: ["simple-http-server"]
                  ports:
                      - name: http
                        containerPort: 8000
                  resources:
                      requests:
                          cpu: 100m
                          memory: 100Mi
                      limits:
                          cpu: 200m
                          memory: 200Mi
                  readinessProbe:
                      httpGet:
                          path: /ok
                          port: 8000
                          scheme: HTTP
                      initialDelaySeconds: 2
                      timeoutSeconds: 2
                      periodSeconds: 10
                  livenessProbe:
                      httpGet:
                          path: /ok
                          port: 8000
                          scheme: HTTP
                      initialDelaySeconds: 3
                      timeoutSeconds: 2
                      periodSeconds: 30
